// Equipment Pre-Use Inspection Checklist Data
// Only includes PRE-inspection items (no post-inspection)

export interface ChecklistItem {
  id: string;
  text: string;
}

export interface ChecklistSection {
  id: string;
  title: string;
  items: ChecklistItem[];
}

export interface EquipmentType {
  id: string;
  name: string;
  description: string;
  icon: string;
  standard: string;
  sections: ChecklistSection[];
}

export const equipmentChecklists: EquipmentType[] = [
  {
    id: 'swing-stage',
    name: 'Swing Stage',
    description: 'Suspended scaffold pre-use inspection',
    icon: 'swing-stage',
    standard: 'CSA Z271',
    sections: [
      {
        id: 'documentation',
        title: '1. Pre-Use Documentation & Qualifications',
        items: [
          { id: 'doc-1', text: 'Valid swing stage operator certification on file' },
          { id: 'doc-2', text: 'Fall protection training completed and documented' },
          { id: 'doc-3', text: 'Equipment inspection log reviewed' },
          { id: 'doc-4', text: "Manufacturer's operating manual available on site" },
          { id: 'doc-5', text: 'Engineering drawings/specifications available (if required)' },
          { id: 'doc-6', text: 'Rescue plan documented and communicated' },
          { id: 'doc-7', text: 'Workers briefed on emergency procedures' },
          { id: 'doc-8', text: 'Site-specific hazard assessment completed' },
        ],
      },
      {
        id: 'rigging',
        title: '2. Rigging & Suspension System',
        items: [
          { id: 'rig-1', text: 'Roof rigging/outriggers properly installed and secured' },
          { id: 'rig-2', text: 'Counterweights adequate and properly secured' },
          { id: 'rig-3', text: 'Parapet clamps/tie-backs properly installed' },
          { id: 'rig-4', text: 'Roof anchors inspected and certified' },
          { id: 'rig-5', text: 'Wire ropes free of kinks, bird caging, or broken strands' },
          { id: 'rig-6', text: 'Wire rope clips properly installed (U-bolt on dead end)' },
          { id: 'rig-7', text: 'Thimbles installed at all connection points' },
          { id: 'rig-8', text: 'Secondary/safety wire ropes in place' },
          { id: 'rig-9', text: 'All shackles, hooks, and hardware in good condition' },
          { id: 'rig-10', text: 'Load capacity clearly marked and not exceeded' },
        ],
      },
      {
        id: 'platform',
        title: '3. Platform/Deck Inspection',
        items: [
          { id: 'plat-1', text: 'Platform deck in good condition (no cracks, holes, rot)' },
          { id: 'plat-2', text: 'Platform level and properly aligned' },
          { id: 'plat-3', text: 'All platform sections securely connected' },
          { id: 'plat-4', text: 'Stirrups/hangers properly attached to platform' },
          { id: 'plat-5', text: 'No excessive debris or materials on platform' },
          { id: 'plat-6', text: 'Platform width adequate for work being performed' },
          { id: 'plat-7', text: 'End gates/access points secure' },
        ],
      },
      {
        id: 'guardrails',
        title: '4. Guardrails & Fall Protection',
        items: [
          { id: 'guard-1', text: 'Top rail at 1.0m - 1.1m (39" - 42") height' },
          { id: 'guard-2', text: 'Mid rail installed at approximately half height' },
          { id: 'guard-3', text: 'Toeboards minimum 100mm (4") height installed' },
          { id: 'guard-4', text: 'All guardrail connections secure' },
          { id: 'guard-5', text: 'Guardrails on all open sides of platform' },
          { id: 'guard-6', text: 'Independent lifelines properly installed' },
          { id: 'guard-7', text: 'Lifeline anchors rated for fall arrest loads' },
          { id: 'guard-8', text: 'Rope grabs/fall arresters functioning properly' },
        ],
      },
      {
        id: 'hoisting',
        title: '5. Hoisting Equipment',
        items: [
          { id: 'hoist-1', text: 'Hoists securely mounted to stirrups' },
          { id: 'hoist-2', text: 'Hoist motors in good working condition' },
          { id: 'hoist-3', text: 'Primary brake functioning properly' },
          { id: 'hoist-4', text: 'Secondary/emergency brake functioning' },
          { id: 'hoist-5', text: 'Upper and lower limit switches operational' },
          { id: 'hoist-6', text: 'Control switches clearly labeled and functional' },
          { id: 'hoist-7', text: 'Emergency stop button accessible and working' },
          { id: 'hoist-8', text: 'Hoist rated capacity clearly marked' },
          { id: 'hoist-9', text: 'Hoists synchronized for level operation' },
        ],
      },
      {
        id: 'electrical',
        title: '6. Electrical Systems',
        items: [
          { id: 'elec-1', text: 'Power supply adequate for equipment load' },
          { id: 'elec-2', text: 'GFCI protection in place' },
          { id: 'elec-3', text: 'Power cables in good condition (no cuts, fraying)' },
          { id: 'elec-4', text: 'Cables properly secured and protected' },
          { id: 'elec-5', text: 'Electrical connections weatherproof' },
          { id: 'elec-6', text: 'Minimum clearance from power lines maintained' },
          { id: 'elec-7', text: 'Control pendant in good condition' },
        ],
      },
      {
        id: 'ppe',
        title: '7. Personal Protective Equipment',
        items: [
          { id: 'ppe-1', text: 'CSA-approved full body harness worn' },
          { id: 'ppe-2', text: 'Harness inspected and in good condition' },
          { id: 'ppe-3', text: 'Shock-absorbing lanyard or SRL connected' },
          { id: 'ppe-4', text: 'Lanyard connected to independent lifeline' },
          { id: 'ppe-5', text: 'Hard hat worn at all times' },
          { id: 'ppe-6', text: 'Safety footwear worn' },
          { id: 'ppe-7', text: 'High-visibility vest worn' },
          { id: 'ppe-8', text: 'Additional PPE as required (gloves, eye protection)' },
        ],
      },
      {
        id: 'weather',
        title: '8. Weather & Environmental Conditions',
        items: [
          { id: 'weath-1', text: 'Wind speed within safe operating limits (typically <40 km/h)' },
          { id: 'weath-2', text: 'No lightning or electrical storms in area' },
          { id: 'weath-3', text: 'Visibility adequate for safe operation' },
          { id: 'weath-4', text: 'Platform not icy or slippery' },
          { id: 'weath-5', text: 'No heavy rain or snow affecting operation' },
          { id: 'weath-6', text: 'Temperature within equipment operating range' },
        ],
      },
      {
        id: 'site',
        title: '9. Site Conditions & Hazards',
        items: [
          { id: 'site-1', text: 'Area below platform barricaded/controlled' },
          { id: 'site-2', text: 'Warning signs posted at ground level' },
          { id: 'site-3', text: 'No obstructions in travel path' },
          { id: 'site-4', text: 'Building features/projections identified' },
          { id: 'site-5', text: 'Communication system in place' },
          { id: 'site-6', text: 'Spotter/ground person assigned if required' },
          { id: 'site-7', text: 'Emergency access route identified' },
        ],
      },
      {
        id: 'operational',
        title: '10. Operational Test',
        items: [
          { id: 'op-1', text: 'Platform raised and lowered through full range' },
          { id: 'op-2', text: 'Platform remains level during operation' },
          { id: 'op-3', text: 'Brakes tested and holding properly' },
          { id: 'op-4', text: 'Limit switches tested and functioning' },
          { id: 'op-5', text: 'Emergency stop tested' },
          { id: 'op-6', text: 'No unusual sounds or vibrations' },
          { id: 'op-7', text: 'Manual descent procedure verified' },
        ],
      },
    ],
  },
  {
    id: 'scissor-lift',
    name: 'Scissor Lift',
    description: 'Mobile elevating work platform pre-use inspection',
    icon: 'scissor-lift',
    standard: 'CSA B354.2',
    sections: [
      {
        id: 'documentation',
        title: '1. Documentation & Training',
        items: [
          { id: 'doc-1', text: 'Operator trained and authorized to use equipment' },
          { id: 'doc-2', text: 'Valid operator certification on file' },
          { id: 'doc-3', text: "Manufacturer's operating manual available" },
          { id: 'doc-4', text: 'Equipment inspection log reviewed' },
          { id: 'doc-5', text: 'Site-specific hazard assessment completed' },
        ],
      },
      {
        id: 'base-chassis',
        title: '2. Base/Chassis Inspection',
        items: [
          { id: 'base-1', text: 'Tires in good condition with proper inflation' },
          { id: 'base-2', text: 'No visible damage to frame or chassis' },
          { id: 'base-3', text: 'Outriggers/stabilizers functioning (if equipped)' },
          { id: 'base-4', text: 'Drive motors operating properly' },
          { id: 'base-5', text: 'Steering responsive and functioning' },
          { id: 'base-6', text: 'Brakes holding properly' },
          { id: 'base-7', text: 'No fluid leaks (hydraulic, fuel, battery acid)' },
        ],
      },
      {
        id: 'scissor-mechanism',
        title: '3. Scissor Mechanism',
        items: [
          { id: 'mech-1', text: 'Scissor arms free of damage, cracks, or corrosion' },
          { id: 'mech-2', text: 'All pivot pins and bolts secure' },
          { id: 'mech-3', text: 'Hydraulic cylinders free of leaks' },
          { id: 'mech-4', text: 'Hydraulic hoses in good condition' },
          { id: 'mech-5', text: 'Lift mechanism operates smoothly' },
          { id: 'mech-6', text: 'No unusual sounds during operation' },
        ],
      },
      {
        id: 'platform',
        title: '4. Platform/Work Area',
        items: [
          { id: 'plat-1', text: 'Platform floor in good condition (no holes, damage)' },
          { id: 'plat-2', text: 'Guardrails secure at proper height (1.0m - 1.1m)' },
          { id: 'plat-3', text: 'Mid-rails installed and secure' },
          { id: 'plat-4', text: 'Toeboards in place (minimum 100mm height)' },
          { id: 'plat-5', text: 'Entry gate/chain functioning properly' },
          { id: 'plat-6', text: 'Platform extension (if equipped) functioning' },
          { id: 'plat-7', text: 'Load capacity placard visible and legible' },
        ],
      },
      {
        id: 'controls',
        title: '5. Controls & Safety Devices',
        items: [
          { id: 'ctrl-1', text: 'Ground controls functioning properly' },
          { id: 'ctrl-2', text: 'Platform controls functioning properly' },
          { id: 'ctrl-3', text: 'Emergency stop buttons working (ground and platform)' },
          { id: 'ctrl-4', text: 'Emergency lowering system operational' },
          { id: 'ctrl-5', text: 'Tilt alarm/sensor functioning' },
          { id: 'ctrl-6', text: 'Descent alarm/warning functioning' },
          { id: 'ctrl-7', text: 'Control labels legible' },
          { id: 'ctrl-8', text: 'Key switch/enable switch functioning' },
        ],
      },
      {
        id: 'electrical',
        title: '6. Electrical/Power System',
        items: [
          { id: 'elec-1', text: 'Battery charge adequate for work' },
          { id: 'elec-2', text: 'Battery connections clean and tight' },
          { id: 'elec-3', text: 'No damaged wiring or exposed conductors' },
          { id: 'elec-4', text: 'Charger functioning properly (if applicable)' },
          { id: 'elec-5', text: 'Fuel level adequate (for engine-powered units)' },
        ],
      },
      {
        id: 'site',
        title: '7. Site Conditions',
        items: [
          { id: 'site-1', text: 'Ground surface firm and level' },
          { id: 'site-2', text: 'No overhead obstructions or hazards' },
          { id: 'site-3', text: 'Adequate clearance from power lines' },
          { id: 'site-4', text: 'Work area barricaded if required' },
          { id: 'site-5', text: 'Wind conditions within safe limits' },
          { id: 'site-6', text: 'No floor openings or drop-offs in travel path' },
        ],
      },
    ],
  },
  {
    id: 'boom-lift',
    name: 'Boom Lift',
    description: 'Articulating/telescopic boom lift pre-use inspection',
    icon: 'boom-lift',
    standard: 'CSA B354.4',
    sections: [
      {
        id: 'documentation',
        title: '1. Documentation & Training',
        items: [
          { id: 'doc-1', text: 'Operator trained and authorized for this equipment type' },
          { id: 'doc-2', text: 'Valid operator certification on file' },
          { id: 'doc-3', text: "Manufacturer's operating manual available" },
          { id: 'doc-4', text: 'Equipment inspection log reviewed' },
          { id: 'doc-5', text: 'Site-specific hazard assessment completed' },
          { id: 'doc-6', text: 'Fall protection training completed' },
        ],
      },
      {
        id: 'base-chassis',
        title: '2. Base/Chassis Inspection',
        items: [
          { id: 'base-1', text: 'Tires in good condition with proper inflation' },
          { id: 'base-2', text: 'No visible damage to frame or chassis' },
          { id: 'base-3', text: 'Outriggers/stabilizers functioning (if equipped)' },
          { id: 'base-4', text: 'Drive system operating properly' },
          { id: 'base-5', text: 'Steering responsive and functioning' },
          { id: 'base-6', text: 'Brakes holding properly' },
          { id: 'base-7', text: 'No fluid leaks (hydraulic, fuel, coolant)' },
          { id: 'base-8', text: 'Turntable rotation smooth and controlled' },
        ],
      },
      {
        id: 'boom-system',
        title: '3. Boom System',
        items: [
          { id: 'boom-1', text: 'Boom sections free of damage, cracks, or corrosion' },
          { id: 'boom-2', text: 'All pivot pins and bolts secure' },
          { id: 'boom-3', text: 'Hydraulic cylinders free of leaks' },
          { id: 'boom-4', text: 'Hydraulic hoses in good condition' },
          { id: 'boom-5', text: 'Boom extends and retracts smoothly' },
          { id: 'boom-6', text: 'Articulating joint functioning (if equipped)' },
          { id: 'boom-7', text: 'Jib functioning properly (if equipped)' },
          { id: 'boom-8', text: 'No unusual sounds during operation' },
        ],
      },
      {
        id: 'platform',
        title: '4. Platform/Basket',
        items: [
          { id: 'plat-1', text: 'Platform floor in good condition' },
          { id: 'plat-2', text: 'Guardrails secure at proper height' },
          { id: 'plat-3', text: 'Mid-rails installed and secure' },
          { id: 'plat-4', text: 'Toeboards in place' },
          { id: 'plat-5', text: 'Entry gate/chain functioning properly' },
          { id: 'plat-6', text: 'Platform rotator functioning (if equipped)' },
          { id: 'plat-7', text: 'Lanyard anchor points in good condition' },
          { id: 'plat-8', text: 'Load capacity placard visible and legible' },
        ],
      },
      {
        id: 'controls',
        title: '5. Controls & Safety Devices',
        items: [
          { id: 'ctrl-1', text: 'Ground controls functioning properly' },
          { id: 'ctrl-2', text: 'Platform controls functioning properly' },
          { id: 'ctrl-3', text: 'Emergency stop buttons working (ground and platform)' },
          { id: 'ctrl-4', text: 'Emergency lowering system operational' },
          { id: 'ctrl-5', text: 'Tilt alarm/sensor functioning' },
          { id: 'ctrl-6', text: 'Load sensing system functioning' },
          { id: 'ctrl-7', text: 'Control labels legible' },
          { id: 'ctrl-8', text: 'Boom/platform limit switches functioning' },
        ],
      },
      {
        id: 'fall-protection',
        title: '6. Fall Protection',
        items: [
          { id: 'fp-1', text: 'Full body harness available and inspected' },
          { id: 'fp-2', text: 'Lanyard in good condition' },
          { id: 'fp-3', text: 'Anchor points on platform in good condition' },
          { id: 'fp-4', text: 'Fall protection required and will be worn' },
        ],
      },
      {
        id: 'site',
        title: '7. Site Conditions',
        items: [
          { id: 'site-1', text: 'Ground surface firm and level' },
          { id: 'site-2', text: 'No overhead obstructions or hazards identified' },
          { id: 'site-3', text: 'Adequate clearance from power lines (min 3m)' },
          { id: 'site-4', text: 'Work area barricaded if required' },
          { id: 'site-5', text: 'Wind conditions within safe limits' },
          { id: 'site-6', text: 'Underground hazards identified and marked' },
        ],
      },
    ],
  },
  {
    id: 'forklift',
    name: 'Forklift',
    description: 'Powered industrial truck pre-use inspection',
    icon: 'forklift',
    standard: 'CSA B335',
    sections: [
      {
        id: 'documentation',
        title: '1. Documentation & Training',
        items: [
          { id: 'doc-1', text: 'Operator trained and certified for this forklift type' },
          { id: 'doc-2', text: 'Valid operator certification on file' },
          { id: 'doc-3', text: 'Equipment inspection log reviewed' },
          { id: 'doc-4', text: 'Load capacity chart visible and legible' },
        ],
      },
      {
        id: 'visual',
        title: '2. Visual Inspection',
        items: [
          { id: 'vis-1', text: 'No visible damage to frame or mast' },
          { id: 'vis-2', text: 'Forks straight and not cracked or worn' },
          { id: 'vis-3', text: 'Fork positioning latch working' },
          { id: 'vis-4', text: 'Backrest extension in place and secure' },
          { id: 'vis-5', text: 'Overhead guard secure and undamaged' },
          { id: 'vis-6', text: 'Data plate legible' },
          { id: 'vis-7', text: 'No fluid leaks (hydraulic, fuel, coolant)' },
        ],
      },
      {
        id: 'tires-wheels',
        title: '3. Tires & Wheels',
        items: [
          { id: 'tire-1', text: 'Tires in good condition (no cuts, chunking, flat spots)' },
          { id: 'tire-2', text: 'Proper tire inflation (pneumatic tires)' },
          { id: 'tire-3', text: 'Wheel nuts/bolts tight' },
          { id: 'tire-4', text: 'No debris wrapped around axles' },
        ],
      },
      {
        id: 'mast-hydraulic',
        title: '4. Mast & Hydraulic System',
        items: [
          { id: 'mast-1', text: 'Mast chains in good condition and properly adjusted' },
          { id: 'mast-2', text: 'Mast rollers and slides lubricated' },
          { id: 'mast-3', text: 'Lift cylinder free of leaks' },
          { id: 'mast-4', text: 'Tilt cylinder free of leaks' },
          { id: 'mast-5', text: 'Hydraulic hoses in good condition' },
          { id: 'mast-6', text: 'Hydraulic fluid level adequate' },
        ],
      },
      {
        id: 'controls',
        title: '5. Controls & Safety Devices',
        items: [
          { id: 'ctrl-1', text: 'Steering responsive and functioning' },
          { id: 'ctrl-2', text: 'Service brake functioning properly' },
          { id: 'ctrl-3', text: 'Parking brake holding' },
          { id: 'ctrl-4', text: 'Horn working' },
          { id: 'ctrl-5', text: 'Backup alarm working' },
          { id: 'ctrl-6', text: 'Lights working (head, tail, warning)' },
          { id: 'ctrl-7', text: 'Lift and tilt controls functioning' },
          { id: 'ctrl-8', text: 'Seat belt present and functional' },
          { id: 'ctrl-9', text: 'Mirrors in place and adjusted' },
        ],
      },
      {
        id: 'power',
        title: '6. Power System',
        items: [
          { id: 'pwr-1', text: 'Battery charge adequate (electric units)' },
          { id: 'pwr-2', text: 'Battery connections clean and tight' },
          { id: 'pwr-3', text: 'Fuel level adequate (IC units)' },
          { id: 'pwr-4', text: 'Propane tank secure and connections tight (LP units)' },
          { id: 'pwr-5', text: 'Engine oil level adequate' },
          { id: 'pwr-6', text: 'Coolant level adequate' },
        ],
      },
      {
        id: 'operational',
        title: '7. Operational Check',
        items: [
          { id: 'op-1', text: 'Mast raises and lowers smoothly' },
          { id: 'op-2', text: 'Mast tilts forward and back smoothly' },
          { id: 'op-3', text: 'Side shift operates (if equipped)' },
          { id: 'op-4', text: 'No unusual noises during operation' },
          { id: 'op-5', text: 'Gauges and indicators functioning' },
        ],
      },
    ],
  },
  {
    id: 'ladder',
    name: 'Ladder',
    description: 'Portable ladder pre-use inspection',
    icon: 'ladder',
    standard: 'CSA Z11',
    sections: [
      {
        id: 'general',
        title: '1. General Inspection',
        items: [
          { id: 'gen-1', text: 'Ladder is appropriate type for the task' },
          { id: 'gen-2', text: 'Ladder rated for required duty (Type I, IA, IAA)' },
          { id: 'gen-3', text: 'Ladder height adequate for work' },
          { id: 'gen-4', text: 'Labels and markings legible' },
          { id: 'gen-5', text: 'No modifications made to ladder' },
        ],
      },
      {
        id: 'structure',
        title: '2. Structural Components',
        items: [
          { id: 'str-1', text: 'Side rails straight and free of damage' },
          { id: 'str-2', text: 'No cracks, splits, or corrosion on rails' },
          { id: 'str-3', text: 'Rungs/steps secure and not bent or damaged' },
          { id: 'str-4', text: 'Rung-to-rail connections tight' },
          { id: 'str-5', text: 'No missing or loose rivets/bolts' },
          { id: 'str-6', text: 'Spreader bars functioning (stepladders)' },
          { id: 'str-7', text: 'Locking mechanisms working (extension ladders)' },
        ],
      },
      {
        id: 'feet-safety',
        title: '3. Feet & Safety Features',
        items: [
          { id: 'feet-1', text: 'Feet/shoes present and in good condition' },
          { id: 'feet-2', text: 'Non-slip feet functioning' },
          { id: 'feet-3', text: 'Rope and pulley in good condition (extension)' },
          { id: 'feet-4', text: 'Rung locks engaging properly (extension)' },
        ],
      },
      {
        id: 'setup',
        title: '4. Setup Conditions',
        items: [
          { id: 'set-1', text: 'Ground surface firm and level' },
          { id: 'set-2', text: 'Proper angle (4:1 ratio for straight/extension)' },
          { id: 'set-3', text: 'Top of ladder extends 1m above landing' },
          { id: 'set-4', text: 'Ladder secured at top or bottom' },
          { id: 'set-5', text: 'Area around ladder clear of hazards' },
          { id: 'set-6', text: 'No electrical hazards nearby' },
          { id: 'set-7', text: 'Stepladder fully open and spreaders locked' },
        ],
      },
    ],
  },
  {
    id: 'scaffold',
    name: 'Scaffold',
    description: 'Frame/system scaffold pre-use inspection',
    icon: 'scaffold',
    standard: 'CSA S269.2',
    sections: [
      {
        id: 'documentation',
        title: '1. Documentation',
        items: [
          { id: 'doc-1', text: 'Scaffold erected by competent person' },
          { id: 'doc-2', text: 'Scaffold design/drawings available (if required)' },
          { id: 'doc-3', text: 'Inspection tag current and signed' },
          { id: 'doc-4', text: 'Load capacity posted' },
        ],
      },
      {
        id: 'base-foundation',
        title: '2. Base & Foundation',
        items: [
          { id: 'base-1', text: 'Base plates/mud sills properly installed' },
          { id: 'base-2', text: 'Foundation firm and level' },
          { id: 'base-3', text: 'Screw jacks properly adjusted' },
          { id: 'base-4', text: 'Casters locked (rolling scaffold)' },
          { id: 'base-5', text: 'Scaffold plumb and level' },
        ],
      },
      {
        id: 'structure',
        title: '3. Structural Components',
        items: [
          { id: 'str-1', text: 'Frames undamaged and properly aligned' },
          { id: 'str-2', text: 'Cross braces in place and secured' },
          { id: 'str-3', text: 'All coupling pins/locks engaged' },
          { id: 'str-4', text: 'No bent or damaged components' },
          { id: 'str-5', text: 'Proper spacing between frames' },
        ],
      },
      {
        id: 'platform',
        title: '4. Platform/Deck',
        items: [
          { id: 'plat-1', text: 'Planks in good condition (no cracks, rot)' },
          { id: 'plat-2', text: 'Planks properly supported and secured' },
          { id: 'plat-3', text: 'Platform fully decked (no gaps >25mm)' },
          { id: 'plat-4', text: 'Planks extend 150-300mm past supports' },
          { id: 'plat-5', text: 'Platform free of debris and tripping hazards' },
        ],
      },
      {
        id: 'guardrails',
        title: '5. Guardrails & Fall Protection',
        items: [
          { id: 'guard-1', text: 'Top rail at 1.0m - 1.1m height' },
          { id: 'guard-2', text: 'Mid-rail installed' },
          { id: 'guard-3', text: 'Toeboards in place (min 100mm)' },
          { id: 'guard-4', text: 'Guardrails on all open sides' },
          { id: 'guard-5', text: 'Access ladder or stairs provided' },
          { id: 'guard-6', text: 'Access opening protected' },
        ],
      },
      {
        id: 'ties',
        title: '6. Ties & Bracing',
        items: [
          { id: 'tie-1', text: 'Ties to structure at required intervals' },
          { id: 'tie-2', text: 'Tie connections secure' },
          { id: 'tie-3', text: 'Guy wires/bracing adequate (freestanding)' },
          { id: 'tie-4', text: 'No unauthorized modifications' },
        ],
      },
    ],
  },
  {
    id: 'excavator',
    name: 'Excavator',
    description: 'Hydraulic excavator pre-use inspection',
    icon: 'excavator',
    standard: 'CSA Z460',
    sections: [
      {
        id: 'documentation',
        title: '1. Documentation & Training',
        items: [
          { id: 'doc-1', text: 'Operator trained and authorized' },
          { id: 'doc-2', text: "Operator's manual available" },
          { id: 'doc-3', text: 'Equipment inspection log reviewed' },
          { id: 'doc-4', text: 'Locate request completed (underground utilities)' },
        ],
      },
      {
        id: 'walkaround',
        title: '2. Walk-Around Inspection',
        items: [
          { id: 'walk-1', text: 'No visible damage to cab or body' },
          { id: 'walk-2', text: 'Windows clean and undamaged' },
          { id: 'walk-3', text: 'Mirrors in place and adjusted' },
          { id: 'walk-4', text: 'Steps and handrails secure' },
          { id: 'walk-5', text: 'No fluid leaks visible' },
          { id: 'walk-6', text: 'Fire extinguisher present and charged' },
        ],
      },
      {
        id: 'undercarriage',
        title: '3. Undercarriage',
        items: [
          { id: 'under-1', text: 'Tracks properly tensioned' },
          { id: 'under-2', text: 'Track pads/shoes in good condition' },
          { id: 'under-3', text: 'Rollers and idlers functioning' },
          { id: 'under-4', text: 'No debris wrapped around components' },
          { id: 'under-5', text: 'Sprockets in good condition' },
        ],
      },
      {
        id: 'boom-arm',
        title: '4. Boom, Arm & Bucket',
        items: [
          { id: 'boom-1', text: 'Boom free of cracks or damage' },
          { id: 'boom-2', text: 'Arm/stick free of damage' },
          { id: 'boom-3', text: 'All pins secure with keepers in place' },
          { id: 'boom-4', text: 'Bucket teeth in good condition' },
          { id: 'boom-5', text: 'Bucket cutting edge adequate' },
          { id: 'boom-6', text: 'Quick coupler functioning (if equipped)' },
          { id: 'boom-7', text: 'Hydraulic cylinders free of leaks' },
          { id: 'boom-8', text: 'Hydraulic hoses in good condition' },
        ],
      },
      {
        id: 'cab-controls',
        title: '5. Cab & Controls',
        items: [
          { id: 'cab-1', text: 'Seat and seat belt in good condition' },
          { id: 'cab-2', text: 'All controls functioning properly' },
          { id: 'cab-3', text: 'Gauges and indicators working' },
          { id: 'cab-4', text: 'Horn working' },
          { id: 'cab-5', text: 'Backup alarm working' },
          { id: 'cab-6', text: 'Lights working' },
          { id: 'cab-7', text: 'HVAC functioning' },
          { id: 'cab-8', text: 'Emergency exits accessible' },
        ],
      },
      {
        id: 'fluids',
        title: '6. Fluids & Engine',
        items: [
          { id: 'fluid-1', text: 'Engine oil level adequate' },
          { id: 'fluid-2', text: 'Hydraulic fluid level adequate' },
          { id: 'fluid-3', text: 'Coolant level adequate' },
          { id: 'fluid-4', text: 'Fuel level adequate' },
          { id: 'fluid-5', text: 'Air filter indicator checked' },
          { id: 'fluid-6', text: 'DEF level adequate (if equipped)' },
        ],
      },
      {
        id: 'safety',
        title: '7. Safety Systems',
        items: [
          { id: 'safe-1', text: 'ROPS/FOPS structure undamaged' },
          { id: 'safe-2', text: 'Travel alarm functioning' },
          { id: 'safe-3', text: 'Swing alarm functioning (if equipped)' },
          { id: 'safe-4', text: 'Camera systems working (if equipped)' },
          { id: 'safe-5', text: 'Proximity warning system functioning (if equipped)' },
        ],
      },
    ],
  },
  {
    id: 'telehandler',
    name: 'Telehandler',
    description: 'Telescopic handler pre-use inspection',
    icon: 'telehandler',
    standard: 'CSA B354.1',
    sections: [
      {
        id: 'documentation',
        title: '1. Documentation & Training',
        items: [
          { id: 'doc-1', text: 'Operator trained and authorized' },
          { id: 'doc-2', text: 'Valid certification on file' },
          { id: 'doc-3', text: "Operator's manual available" },
          { id: 'doc-4', text: 'Load chart available and understood' },
          { id: 'doc-5', text: 'Equipment inspection log reviewed' },
        ],
      },
      {
        id: 'walkaround',
        title: '2. Walk-Around Inspection',
        items: [
          { id: 'walk-1', text: 'No visible damage to cab or frame' },
          { id: 'walk-2', text: 'Windows clean and undamaged' },
          { id: 'walk-3', text: 'Mirrors in place and adjusted' },
          { id: 'walk-4', text: 'Steps and handrails secure' },
          { id: 'walk-5', text: 'No fluid leaks visible' },
          { id: 'walk-6', text: 'Fire extinguisher present and charged' },
        ],
      },
      {
        id: 'tires',
        title: '3. Tires & Wheels',
        items: [
          { id: 'tire-1', text: 'Tires in good condition' },
          { id: 'tire-2', text: 'Proper tire inflation' },
          { id: 'tire-3', text: 'Wheel nuts tight' },
          { id: 'tire-4', text: 'No cuts or damage to sidewalls' },
        ],
      },
      {
        id: 'boom',
        title: '4. Boom & Attachment',
        items: [
          { id: 'boom-1', text: 'Boom sections free of damage' },
          { id: 'boom-2', text: 'Boom extends and retracts smoothly' },
          { id: 'boom-3', text: 'Hydraulic cylinders free of leaks' },
          { id: 'boom-4', text: 'Hydraulic hoses in good condition' },
          { id: 'boom-5', text: 'Attachment mounting secure' },
          { id: 'boom-6', text: 'Quick attach functioning properly' },
          { id: 'boom-7', text: 'Forks straight and undamaged (if equipped)' },
          { id: 'boom-8', text: 'Fork positioning latch working' },
        ],
      },
      {
        id: 'cab-controls',
        title: '5. Cab & Controls',
        items: [
          { id: 'cab-1', text: 'Seat and seat belt functioning' },
          { id: 'cab-2', text: 'All controls functioning properly' },
          { id: 'cab-3', text: 'Gauges and indicators working' },
          { id: 'cab-4', text: 'Horn working' },
          { id: 'cab-5', text: 'Backup alarm working' },
          { id: 'cab-6', text: 'Lights working' },
          { id: 'cab-7', text: 'Steering responsive' },
          { id: 'cab-8', text: 'Brakes functioning properly' },
        ],
      },
      {
        id: 'stabilizers',
        title: '6. Stabilizers/Outriggers',
        items: [
          { id: 'stab-1', text: 'Stabilizers extend and retract properly' },
          { id: 'stab-2', text: 'Stabilizer pads in good condition' },
          { id: 'stab-3', text: 'Stabilizer cylinders free of leaks' },
          { id: 'stab-4', text: 'Stabilizer locks engaging' },
        ],
      },
      {
        id: 'safety',
        title: '7. Safety Systems',
        items: [
          { id: 'safe-1', text: 'Load moment indicator functioning' },
          { id: 'safe-2', text: 'Overload warning system working' },
          { id: 'safe-3', text: 'Frame level indicator working' },
          { id: 'safe-4', text: 'ROPS/FOPS structure undamaged' },
          { id: 'safe-5', text: 'Camera systems working (if equipped)' },
        ],
      },
    ],
  },
  {
    id: 'mobile-crane',
    name: 'Mobile Crane',
    description: 'Mobile crane pre-use inspection',
    icon: 'crane',
    standard: 'CSA Z150',
    sections: [
      {
        id: 'documentation',
        title: '1. Documentation & Certification',
        items: [
          { id: 'doc-1', text: 'Operator certified for crane type and capacity' },
          { id: 'doc-2', text: 'Valid operator certification on file' },
          { id: 'doc-3', text: 'Crane certification current' },
          { id: 'doc-4', text: 'Load charts available and legible' },
          { id: 'doc-5', text: "Operator's manual available" },
          { id: 'doc-6', text: 'Lift plan completed (if required)' },
          { id: 'doc-7', text: 'Equipment inspection log reviewed' },
        ],
      },
      {
        id: 'walkaround',
        title: '2. Walk-Around Inspection',
        items: [
          { id: 'walk-1', text: 'No visible damage to cab or superstructure' },
          { id: 'walk-2', text: 'Windows clean and undamaged' },
          { id: 'walk-3', text: 'Steps and handrails secure' },
          { id: 'walk-4', text: 'No fluid leaks visible' },
          { id: 'walk-5', text: 'Fire extinguisher present and charged' },
          { id: 'walk-6', text: 'All guards and covers in place' },
        ],
      },
      {
        id: 'carrier',
        title: '3. Carrier/Base',
        items: [
          { id: 'car-1', text: 'Tires in good condition with proper inflation' },
          { id: 'car-2', text: 'Wheel nuts tight' },
          { id: 'car-3', text: 'Outriggers functioning properly' },
          { id: 'car-4', text: 'Outrigger pads available and adequate' },
          { id: 'car-5', text: 'Outrigger cylinders free of leaks' },
          { id: 'car-6', text: 'Swing bearing/turntable lubricated' },
        ],
      },
      {
        id: 'boom',
        title: '4. Boom System',
        items: [
          { id: 'boom-1', text: 'Boom sections free of damage, cracks, or dents' },
          { id: 'boom-2', text: 'Boom extends and retracts smoothly' },
          { id: 'boom-3', text: 'Boom hoist functioning properly' },
          { id: 'boom-4', text: 'Boom angle indicator working' },
          { id: 'boom-5', text: 'Boom length indicator working' },
          { id: 'boom-6', text: 'Jib in good condition (if equipped)' },
          { id: 'boom-7', text: 'Pendant lines in good condition' },
        ],
      },
      {
        id: 'wire-rope',
        title: '5. Wire Rope & Rigging',
        items: [
          { id: 'wire-1', text: 'Wire rope free of kinks, bird caging, or broken strands' },
          { id: 'wire-2', text: 'Wire rope properly reeved' },
          { id: 'wire-3', text: 'Minimum wraps on drum maintained' },
          { id: 'wire-4', text: 'Hook block in good condition' },
          { id: 'wire-5', text: 'Hook safety latch functioning' },
          { id: 'wire-6', text: 'Sheaves in good condition' },
          { id: 'wire-7', text: 'Anti-two block device functioning' },
        ],
      },
      {
        id: 'controls',
        title: '6. Controls & Safety Devices',
        items: [
          { id: 'ctrl-1', text: 'All controls functioning properly' },
          { id: 'ctrl-2', text: 'Load moment indicator (LMI) functioning' },
          { id: 'ctrl-3', text: 'Rated capacity indicator (RCI) functioning' },
          { id: 'ctrl-4', text: 'Boom angle/length limits functioning' },
          { id: 'ctrl-5', text: 'Swing brake functioning' },
          { id: 'ctrl-6', text: 'Hoist brake functioning' },
          { id: 'ctrl-7', text: 'Emergency stop accessible and working' },
          { id: 'ctrl-8', text: 'Horn working' },
        ],
      },
      {
        id: 'site',
        title: '7. Site Conditions',
        items: [
          { id: 'site-1', text: 'Ground conditions adequate for setup' },
          { id: 'site-2', text: 'Adequate clearance from power lines' },
          { id: 'site-3', text: 'Swing radius clear of obstructions' },
          { id: 'site-4', text: 'Work area barricaded' },
          { id: 'site-5', text: 'Wind conditions within limits' },
          { id: 'site-6', text: 'Signal person designated (if required)' },
        ],
      },
    ],
  },
  {
    id: 'skid-steer',
    name: 'Skid Steer',
    description: 'Skid steer loader pre-use inspection',
    icon: 'skid-steer',
    standard: 'CSA Z460',
    sections: [
      {
        id: 'documentation',
        title: '1. Documentation & Training',
        items: [
          { id: 'doc-1', text: 'Operator trained and authorized' },
          { id: 'doc-2', text: "Operator's manual available" },
          { id: 'doc-3', text: 'Equipment inspection log reviewed' },
        ],
      },
      {
        id: 'walkaround',
        title: '2. Walk-Around Inspection',
        items: [
          { id: 'walk-1', text: 'No visible damage to cab or frame' },
          { id: 'walk-2', text: 'Windows/door clean and undamaged' },
          { id: 'walk-3', text: 'ROPS/FOPS structure undamaged' },
          { id: 'walk-4', text: 'No fluid leaks visible' },
          { id: 'walk-5', text: 'Fire extinguisher present (if required)' },
          { id: 'walk-6', text: 'All guards and covers in place' },
        ],
      },
      {
        id: 'tires-tracks',
        title: '3. Tires/Tracks',
        items: [
          { id: 'tire-1', text: 'Tires in good condition (wheeled units)' },
          { id: 'tire-2', text: 'Proper tire inflation' },
          { id: 'tire-3', text: 'Tracks properly tensioned (tracked units)' },
          { id: 'tire-4', text: 'Track pads in good condition' },
          { id: 'tire-5', text: 'Wheel nuts/track bolts tight' },
        ],
      },
      {
        id: 'lift-arms',
        title: '4. Lift Arms & Attachment',
        items: [
          { id: 'lift-1', text: 'Lift arms free of damage or cracks' },
          { id: 'lift-2', text: 'Lift arm pins secure' },
          { id: 'lift-3', text: 'Hydraulic cylinders free of leaks' },
          { id: 'lift-4', text: 'Hydraulic hoses in good condition' },
          { id: 'lift-5', text: 'Quick attach plate functioning' },
          { id: 'lift-6', text: 'Attachment properly secured' },
          { id: 'lift-7', text: 'Bucket cutting edge adequate' },
        ],
      },
      {
        id: 'cab-controls',
        title: '5. Cab & Controls',
        items: [
          { id: 'cab-1', text: 'Seat and seat belt/bar functioning' },
          { id: 'cab-2', text: 'All controls functioning properly' },
          { id: 'cab-3', text: 'Gauges and indicators working' },
          { id: 'cab-4', text: 'Horn working' },
          { id: 'cab-5', text: 'Backup alarm working' },
          { id: 'cab-6', text: 'Lights working' },
          { id: 'cab-7', text: 'Door/restraint bar interlock functioning' },
        ],
      },
      {
        id: 'fluids',
        title: '6. Fluids & Engine',
        items: [
          { id: 'fluid-1', text: 'Engine oil level adequate' },
          { id: 'fluid-2', text: 'Hydraulic fluid level adequate' },
          { id: 'fluid-3', text: 'Coolant level adequate' },
          { id: 'fluid-4', text: 'Fuel level adequate' },
          { id: 'fluid-5', text: 'Air filter indicator checked' },
        ],
      },
      {
        id: 'operational',
        title: '7. Operational Check',
        items: [
          { id: 'op-1', text: 'Lift arms raise and lower smoothly' },
          { id: 'op-2', text: 'Bucket/attachment tilts properly' },
          { id: 'op-3', text: 'Drive system responds properly' },
          { id: 'op-4', text: 'Brakes functioning' },
          { id: 'op-5', text: 'No unusual noises or vibrations' },
        ],
      },
    ],
  },
];

export const getEquipmentById = (id: string): EquipmentType | undefined => {
  return equipmentChecklists.find(eq => eq.id === id);
};

export const getEquipmentList = () => {
  return equipmentChecklists.map(eq => ({
    id: eq.id,
    name: eq.name,
    description: eq.description,
    icon: eq.icon,
    standard: eq.standard,
    sectionCount: eq.sections.length,
    itemCount: eq.sections.reduce((acc, section) => acc + section.items.length, 0),
  }));
};
